FROM rocker/tidyverse:3.5.1

# Install Azure CLI
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gnupg

RUN AZ_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
        tee /etc/apt/sources.list.d/azure-cli.list && \
    curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    apt-get install apt-transport-https && \
    apt-get update && apt-get install azure-cli

# Install conda (from https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/Dockerfile)
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && apt-get install -y wget bzip2

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc


# Install additional r packages
RUN R -e "devtools::install_github('Azure/rAzureBatch')"
RUN R -e "devtools::install_github('Azure/doAzureParallel')"
RUN R -e "devtools::install_github('carlanetto/M4comp2018')"
RUN R -e "install.packages(c('doParallel', 'forecast', 'opera', 'forecastHybrid', 'argparse', 'dotenv'))"

RUN mkdir rbatch

WORKDIR /rbatch

CMD ["R"]