# Dockerfile for the worker image

FROM rocker/tidyverse:3.5.1

RUN install2.r --error --repos https://mran.microsoft.com/snapshot/2019-01-07 \
  caret \
  dotenv

RUN r -e 'devtools::install_github("gbm-developers/gbm", \
  ref = "b59270a787202d7ba2de5f2af7032854691d2b10")'
  
RUN r -e 'devtools::install_github("cloudyr/AzureStor", \
  ref = "7d7f03c9d64bed0a076a63437117b21958e75bf9")'

WORKDIR /job

CMD ["R"]